name: Node CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
    tags:
      - '!v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 14.x
        uses: actions/setup-node@v3
        with:
          node-version: 14
          cache: yarn
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Format check
        run: yarn format-check
      - name: Run lint
        run: yarn lint
